export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING';
export const CHANGE_PREORDER_STATUS = 'CHANGE_PREORDER_STATUS';
export const INITIAL_LOGIN_INFO = 'INITIAL_LOGIN_INFO';

export const MEMBERSHIP_DATA = 'MEMBERSHIP_DATA';
export const CURRENT_INDEX = 'CURRENT_INDEX';
export const LAST_INDEX = 'LAST_INDEX';

export const IS_CHAT_OPEN = 'IS_CHAT_OPEN';

export const CHAT_MESSAGE_COUNT = 'CHAT_MESSAGE_COUNT';

export const SAVED_LOCATION = 'SAVED_LOCATION';

export const RESET_ONBOARDING = 'RESET_ONBOARDING';
